import React, { useState } from "react";
import { Clock, Leaf, Package, Lock } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { Progress } from "./ui/progress";
import { motion } from "motion/react";
import { useLanguage } from "../contexts/LanguageContext";

const packingList = {
  "Beach Trip": ["Sunscreen", "Swimsuit", "Sunglasses", "Beach towel", "Flip-flops", "Hat"],
  "Mountain Hike": ["Hiking boots", "Backpack", "Water bottle", "First aid kit", "Jacket", "Trail snacks"],
  "City Tour": ["Comfortable shoes", "Day bag", "Camera", "Power bank", "City map", "Umbrella"],
};


export function WowFeatures() {
  const [selectedPackingCategory, setSelectedPackingCategory] = useState<keyof typeof packingList>("Beach Trip");
  const { t } = useLanguage();

  return (
    <section className="py-20 bg-gradient-to-b from-white to-background">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl mb-4 text-foreground">
            {t('features.title')}
            <span className="block bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
              {t('features.titleHighlight')}
            </span>
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            {t('features.description')}
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8 mb-8">
          {/* Smart Packing */}
          <Card>
            <CardHeader>
              <div className="flex items-center gap-3 mb-2">
                <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-accent to-primary flex items-center justify-center">
                  <Package className="w-5 h-5 text-white" />
                </div>
                <div>
                  <CardTitle>{t('features.smartPacking.title')}</CardTitle>
                  <CardDescription>{t('features.smartPacking.description')}</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex gap-2">
                  {Object.keys(packingList).map((category) => (
                    <Button
                      key={category}
                      variant={selectedPackingCategory === category ? "default" : "outline"}
                      size="sm"
                      onClick={() => setSelectedPackingCategory(category as keyof typeof packingList)}
                      className={selectedPackingCategory === category ? "bg-gradient-to-r from-accent to-primary" : ""}
                    >
                      {category}
                    </Button>
                  ))}
                </div>
                <div className="space-y-2">
                  {packingList[selectedPackingCategory].map((item, index) => (
                    <motion.div
                      key={item}
                      initial={{ opacity: 0, x: -10 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: index * 0.05 }}
                      className="flex items-center gap-3 p-3 bg-muted rounded-lg"
                    >
                      <input type="checkbox" className="w-4 h-4 accent-primary" />
                      <span className="text-sm">{item}</span>
                    </motion.div>
                  ))}
                </div>
                <p className="text-xs text-muted-foreground">
                  {t('features.smartPacking.autoGenerated')}
                </p>
              </div>
            </CardContent>
          </Card>

          {/* Layover Planner */}
          <Card>
            <CardHeader>
              <div className="flex items-center gap-3 mb-2">
                <div className="w-10 h-10 rounded-lg  bg-primary  flex items-center justify-center">
                  <Clock className="w-5 h-5 text-white" />
                </div>
                <div>
                  <CardTitle>{t('features.layoverOptimizer.title')}</CardTitle>
                  <CardDescription>{t('features.layoverOptimizer.description')}</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="p-4 bg-muted rounded-lg opacity-60">
                  <div className="flex justify-between items-center mb-2">
                    <span className="text-sm">{t('features.layoverOptimizer.example')}</span>
                    <Badge>{t('features.layoverOptimizer.duration')}</Badge>
                  </div>
                  <p className="text-sm text-muted-foreground mb-3">
                    {t('features.layoverOptimizer.descriptionText')}
                  </p>
                  <div className="space-y-2 text-sm">
                    <div className="flex items-center gap-2">
                      <div className="w-2 h-2 rounded-full bg-primary"></div>
                      <span>{t('features.layoverOptimizer.itinerary.airportToCity')}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="w-2 h-2 rounded-full bg-primary text-primary"></div>
                      <span>{t('features.layoverOptimizer.itinerary.colosseum')}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="w-2 h-2 rounded-full bg-primary"></div>
                      <span>{t('features.layoverOptimizer.itinerary.lunch')}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="w-2 h-2 rounded-full bg-primary"></div>
                      <span>{t('features.layoverOptimizer.itinerary.pantheon')}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="w-2 h-2 rounded-full bg-primary"></div>
                      <span>{t('features.layoverOptimizer.itinerary.returnToAirport')}</span>
                    </div>
                  </div>
                </div>
                <div className="space-y-2">
                  <Button 
                    className="w-full bg-primary cursor-not-allowed hover:bg-gray-300" 
                    disabled
                  >
                    <Lock className="w-4 h-4 mr-2" />
                    {t('features.layoverOptimizer.createPlan')}
                  </Button>
                  <div className="mt-6 p-4 bg-gradient-to-r from-amber-50 to-orange-50 border border-amber-200 rounded-lg">
                        <div className="flex items-center gap-3 mb-3">
                          <div className="w-8 h-8 rounded-full bg-gradient-to-r from-amber-500 to-orange-500 flex items-center justify-center">
                            <Lock className="w-4 h-4 text-primary" />
                          </div>
                          <div>
                            <h4 className="font-semibold text-amber-800">Premium Required</h4>
                            <p className="text-sm text-amber-700">Switch to premium plan to continue with chat history</p>
                          </div>
                        </div>
                        <Button
                          className="w-full bg-gradient-to-r from-primary to-secondary hover:from-primary/80 hover:to-secondary/80 text-white"
                          size="sm"
                        >
                          Upgrade to Premium
                        </Button>
                      </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  );
}